#!/usr/bin/env node
/**
 * Embeds pre-built Acurast processor bundles into the Next.js frontend as
 * TypeScript constants. Serverless functions cannot rely on repo-relative
 * filesystem access at runtime, so deployment routes import these constants
 * when uploading scripts to IPFS.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LIB_DIR = path.join(ROOT, 'frontend', 'src', 'lib');

const BUNDLES = [
  {
    source: path.join(ROOT, 'dist', 'processor.bundle.cjs'),
    destination: path.join(LIB_DIR, 'processorBundle.ts'),
    exportName: 'PROCESSOR_BUNDLE',
    routeHint: '/api/deploy and the grid Acurast deployment adapter',
  },
  {
    source: path.join(ROOT, 'dist', 'index.bundle.cjs'),
    destination: path.join(LIB_DIR, 'yieldProcessorBundle.ts'),
    exportName: 'YIELD_PROCESSOR_BUNDLE',
    routeHint: 'the yield Acurast deployment adapter',
  },
];

function assertBundleExists(bundle) {
  if (fs.existsSync(bundle.source)) return;

  console.error('');
  console.error('[embedProcessor] FATAL: processor bundle not found.');
  console.error('[embedProcessor]   Expected: ' + bundle.source);
  console.error('[embedProcessor]   Actual cwd: ' + process.cwd());
  console.error('[embedProcessor]   Script dir: ' + __dirname);
  console.error('');
  console.error('[embedProcessor] The root webpack build must complete before this script runs.');
  console.error('[embedProcessor] Fix: run "npm run build:embed" at the repo root before building frontend/.');
  console.error('');
  process.exit(1);
}

function renderBundleModule(bundle, bundleContent) {
  const encoded = JSON.stringify(bundleContent);
  const sizeKB = (bundleContent.length / 1024).toFixed(1);
  const sourcePath = path.relative(ROOT, bundle.source).replace(/\\/g, '/');

  return `// AUTO-GENERATED by scripts/embedProcessor.cjs. DO NOT EDIT MANUALLY
// Regenerate after rebuilding the root project:
//   npm run build:embed
//
// Source: ${sourcePath} (${sizeKB} KB uncompressed)
// Generated: ${new Date().toISOString()}
//
// Why this file exists:
//   ${bundle.routeHint} needs to upload a fully compiled Acurast processor
//   bundle to IPFS at request time. By statically importing this constant,
//   Next.js includes the bundle in the serverless function trace.

export const ${bundle.exportName}: string = ${encoded};
`;
}

fs.mkdirSync(LIB_DIR, { recursive: true });

for (const bundle of BUNDLES) {
  assertBundleExists(bundle);
  const bundleContent = fs.readFileSync(bundle.source, 'utf-8');
  fs.writeFileSync(bundle.destination, renderBundleModule(bundle, bundleContent), 'utf-8');
  console.log(
    `[embedProcessor] ${(bundleContent.length / 1024).toFixed(1)} KB bundle written to ${path
      .relative(ROOT, bundle.destination)
      .replace(/\\/g, '/')}`
  );
}
