#!/usr/bin/env node
/**
 * Embeds the pre-built processor bundle into the Next.js frontend as a TypeScript
 * constant so that Next.js statically traces it into the serverless function bundle
 * at build time.
 *
 * This eliminates all runtime filesystem path resolution — the bundle content is
 * compiled directly into the API route's serverless function, which is the only
 * deployment approach that is guaranteed to work on Netlify, Vercel, and local dev
 * without any path assumptions.
 *
 * Usage:
 *   node scripts/embedProcessor.cjs
 *
 * Run after building the root project:
 *   npm run build && node scripts/embedProcessor.cjs
 */

const fs   = require('fs');
const path = require('path');

const ROOT       = path.resolve(__dirname, '..');
const BUNDLE_SRC = path.join(ROOT, 'dist', 'processor.bundle.cjs');
const LIB_DIR    = path.join(ROOT, 'frontend', 'src', 'lib');
const DEST       = path.join(LIB_DIR, 'processorBundle.ts');

if (!fs.existsSync(BUNDLE_SRC)) {
  console.error('[embedProcessor] ERROR: bundle not found at ' + BUNDLE_SRC);
  console.error('[embedProcessor] Run "npm run build" in the root project first.');
  process.exit(1);
}

const bundleContent = fs.readFileSync(BUNDLE_SRC, 'utf-8');
const sizeKB = (bundleContent.length / 1024).toFixed(1);

// JSON.stringify produces a valid JS string literal with all special characters
// (backslashes, backticks, template-literal delimiters, null bytes) safely escaped.
const encoded = JSON.stringify(bundleContent);

const output = `// AUTO-GENERATED by scripts/embedProcessor.cjs — DO NOT EDIT MANUALLY
// Regenerate after rebuilding the root project:
//   npm run build && node scripts/embedProcessor.cjs
//
// Source: dist/processor.bundle.cjs (${sizeKB} KB uncompressed)
//
// This constant is statically imported by /api/deploy/route.ts so that Next.js
// includes the bundle in the serverless function trace at build time.  This is
// the only reliable way to ship binary/compiled assets to Netlify Lambda or
// Vercel Edge/Node runtimes without filesystem path assumptions.

export const PROCESSOR_BUNDLE: string = ${encoded};
`;

fs.mkdirSync(LIB_DIR, { recursive: true });
fs.writeFileSync(DEST, output, 'utf-8');
console.log('[embedProcessor] ' + sizeKB + ' KB bundle written to frontend/src/lib/processorBundle.ts');
