#!/usr/bin/env node
/**
 * Embeds the pre-built processor bundle into the Next.js frontend as a TypeScript
 * constant so that Next.js statically traces it into the serverless function bundle
 * at build time.
 *
 * This eliminates all runtime filesystem path resolution: the bundle content is
 * compiled directly into the /api/deploy serverless function, which is the only
 * approach guaranteed to work on Netlify, Vercel, and local dev without any
 * process.cwd() or monorepo path assumptions.
 *
 * Correct build order (enforced by netlify.toml and root package.json):
 *   1. cd <repo-root>
 *   2. npm ci                        (install root devDependencies)
 *   3. npm run build:embed           (webpack → dist/processor.bundle.cjs → this script)
 *   4. cd frontend && npm run build  (prebuild re-runs this script, then next build)
 *
 * Running this script without the root webpack build having completed first is
 * an error and will exit non-zero to fail the CI/CD pipeline immediately.
 */

'use strict';

const fs   = require('fs');
const path = require('path');

// __dirname is the absolute path to the scripts/ directory regardless of
// where the script is invoked from.  All paths are anchored here so that
// "cd frontend && node ../scripts/embedProcessor.cjs" and
// "cd repo-root && node scripts/embedProcessor.cjs" produce identical results.
const ROOT       = path.resolve(__dirname, '..');
const BUNDLE_SRC = path.join(ROOT, 'dist', 'processor.bundle.cjs');
const LIB_DIR    = path.join(ROOT, 'frontend', 'src', 'lib');
const DEST       = path.join(LIB_DIR, 'processorBundle.ts');

// ── Pre-flight check ──────────────────────────────────────────────────────────
if (!fs.existsSync(BUNDLE_SRC)) {
  // Surface exactly what went wrong so the engineer doesn't have to guess.
  // On Netlify this appears in the deploy log under the failing step.
  console.error('');
  console.error('[embedProcessor] FATAL: processor bundle not found.');
  console.error('[embedProcessor]   Expected: ' + BUNDLE_SRC);
  console.error('[embedProcessor]   Actual cwd: ' + process.cwd());
  console.error('[embedProcessor]   Script dir: ' + __dirname);
  console.error('');
  console.error('[embedProcessor] The root webpack build must complete before this script runs.');
  console.error('[embedProcessor] Fix: ensure the build command runs "npm run build:embed"');
  console.error('[embedProcessor]      at the repo root BEFORE "npm run build" in frontend/.');
  console.error('[embedProcessor]');
  console.error('[embedProcessor] Netlify build command should be:');
  console.error('[embedProcessor]   cd .. && npm ci && npm run build:embed && cd frontend && npm run build');
  console.error('');
  process.exit(1);
}

// ── Read and embed ────────────────────────────────────────────────────────────
const bundleContent = fs.readFileSync(BUNDLE_SRC, 'utf-8');
const sizeKB = (bundleContent.length / 1024).toFixed(1);

// JSON.stringify produces a valid JS string literal with every special character
// (backslashes, backticks, template-literal delimiters, null bytes) safely escaped.
// This is more reliable than raw template literals or base64 for arbitrary binary-ish
// content that webpack may produce in the bundle.
const encoded = JSON.stringify(bundleContent);

const output = `// AUTO-GENERATED by scripts/embedProcessor.cjs — DO NOT EDIT MANUALLY
// Regenerate after rebuilding the root project:
//   node scripts/embedProcessor.cjs   (from repo root, after "npm run build")
//   — or —
//   npm run build:embed               (runs webpack + this script)
//
// Source: dist/processor.bundle.cjs (${sizeKB} KB uncompressed)
// Generated: ${new Date().toISOString()}
//
// Why this file exists:
//   /api/deploy/route.ts needs to upload a fully-compiled Acurast processor
//   bundle to IPFS at request time.  In a Netlify/Vercel serverless environment
//   there is no access to the repo filesystem (no ../src/processor.ts, no
//   process.cwd() traversal).  By statically importing this constant, Next.js
//   automatically includes it in the serverless function trace at build time,
//   making it available everywhere without any runtime path assumptions.

export const PROCESSOR_BUNDLE: string = ${encoded};
`;

fs.mkdirSync(LIB_DIR, { recursive: true });
fs.writeFileSync(DEST, output, 'utf-8');
console.log('[embedProcessor] ' + sizeKB + ' KB bundle written to frontend/src/lib/processorBundle.ts');
