#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ENV_PATH = path.join(ROOT, ".env");
const OUTPUT_PATH = path.join(ROOT, "src", "generatedEnv.ts");
const includeSecret = process.argv.includes("--include-secret");

const GENERATED_KEYS = [
  "RPC_URL",
  "DATA_RPC_URL",
  "MAINNET_DATA_RPC_URL",
  "YIELD_CHAIN_ID",
  "KEEPER_ADDRESS",
  "POOL_ADDRESS",
  "GAUGE_ADDRESS",
  "UNISWAP_POOL_ADDRESS",
  "USER_ADDRESS",
  "CHAIN_ID",
  "TELEMETRY_URL",
  "TELEMETRY_DIAGNOSTIC_URL",
  "FRONTEND_URL",
  "GRID_CONFIG_JSON",
  "STOP_LOSS_SECRET_JSON",
  "STOP_LOSS_SIGNED_PAYLOAD",
  "FORCE_TEST_HARVEST",
  "FORCE_TEST_ALLOW_MAINNET",
  "DRY_RUN",
  "YIELD_FALLBACK_MODE",
  "POOL_FEE_BPS",
  "EST_GAS_UNITS",
  "HARVEST_MIN_ASSET_OUT",
  "STRATEGY_TVL_USD",
  "EFFICIENCY_MULTIPLIER",
  "MIN_NET_REWARD_USD",
  "MAX_GAS_USD",
  "COOLDOWN_SEC",
  "MIN_APR_CONFIDENCE",
  "MIN_YIELD_CONFIDENCE",
  "RUN_COOLDOWN_GUARD",
  "MIN_RUN_INTERVAL_MS",
  "ENABLE_GRID_KEEPER",
  "STATE_NAMESPACE",
  "RPC_REQUEST_TIMEOUT_MS",
  "RPC_CALL_TIMEOUT_MS",
  "RPC_LOG_TIMEOUT_MS",
  "RPC_CHUNK_DELAY_MS",
];

if (includeSecret) {
  GENERATED_KEYS.push("PROCESSOR_SHARED_SECRET");
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};

  const result = {};
  for (const rawLine of fs.readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const equalsIndex = line.indexOf("=");
    if (equalsIndex === -1) continue;

    const key = line.slice(0, equalsIndex).trim();
    let value = line.slice(equalsIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    result[key] = value;
  }
  return result;
}

const fileEnv = parseEnvFile(ENV_PATH);
const generated = {};

for (const key of GENERATED_KEYS) {
  const value = process.env[key] ?? fileEnv[key];
  if (value != null && String(value).trim() !== "") {
    generated[key] = String(value).trim();
  }
}

const output = `// AUTO-GENERATED by scripts/generateAcurastEnv.cjs. DO NOT COMMIT REAL VALUES.
// This file is intentionally gitignored and exists only to bake CLI deployment
// config into the Acurast bundle when env-var setting is unavailable.
export const GENERATED_ENV: Record<string, string> = ${JSON.stringify(generated, null, 2)};
`;

fs.writeFileSync(OUTPUT_PATH, output, "utf8");
console.log(
  `[generateAcurastEnv] wrote ${Object.keys(generated).length} keys to src/generatedEnv.ts` +
  (includeSecret ? " (including secret)" : " (secret excluded)")
);
